# Generated by Django 5.2.6 on 2025-11-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whopays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payingqueuegroup',
            name='name',
            field=models.CharField(default='Group Name', max_length=100),
            preserve_default=False,
        ),
    ]
