# Generated by Django 5.2.6 on 2025-11-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whopays', '0002_payingqueuegroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payingqueuegroup',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
