# Generated by Django 5.2.6 on 2025-11-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whopays', '0003_alter_payingqueuegroup_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmember',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='groupmember',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
