# Generated by Django 5.2.6 on 2025-11-13 16:08

import whopays.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whopays', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='payingqueuegroup',
            name='emoji',
            field=models.CharField(blank=True, default='👥', help_text='Add an emoji to represent this group.', max_length=15, validators=[whopays.utils.validate_single_emoji]),
        ),
    ]
