# Generated by Django 5.2.6 on 2026-04-30 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whopays', '0009_alter_payingqueuegroup_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payingstate',
            name='current_paying_member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='whopays.groupmember'),
            preserve_default=False,
        ),
    ]
