# Generated by Django 5.2.6 on 2026-05-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whopays', '0010_alter_payingstate_current_paying_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
