# Generated by Django 5.2.6 on 2026-05-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whopays', '0011_alter_groupmember_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payingqueuegroup',
            name='code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
