# Generated by Django 5.2.6 on 2026-05-04 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whopays', '0012_alter_payingqueuegroup_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='groupmember',
            constraint=models.UniqueConstraint(fields=('group', 'order'), name='unique_order_per_group'),
        ),
    ]
