# Generated by Django 5.2.6 on 2026-05-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whopays', '0013_groupmember_unique_order_per_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payingqueuegroup',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
